#! /bin/sh

# Script to compile mhWaveEdit from CVS
# Configure options can be given on command line
# Requires autoconf, automake and some other stuff

cd docgen; sh gendocs.sh; cd ..
aclocal -I m4
autoheader
automake
autoconf
./configure $*
make
